updated with dependency tracking

diff --git a/354tool b/354tool
--- a/354tool
+++ b/354tool
@@ -1,9 +1,18 @@
 #!/bin/bash
 ## configure script variables here
 	CONFIG=config
-	SEMESTER=21s
 	LECTURE_FILE=lec.txt
 ## do not modify below this!
+
+##check dependencies
+	EXPECTED_PYTHON_RES='Python 3*****'
+	if [ $(echo $(python3 -V) | grep -o $EXPECTED_PYTHON_RES | wc -l) -ge 1 ]; then
+		echo 'All dependencies met!'
+	else
+		echo 'Python is not installed and is needed as a dependency for this script.'
+		exit 1
+	fi
+	
 while true
 do
 	echo -e '\033[0;35m####################################################'
@@ -89,7 +98,7 @@ do
 		echo 'Exiting script!'
 		exit 1
 	else
-		echo 'Invalid choice'
+		echo 'Invalid choice!'
 	fi
 done
 	
